### ISSUE TITLE
Clipped Shapes

### ISSUE THREAD

**Issue by zuixalias** [PixelRifts/easy-renderer#1]
Please add fn's to draw clipped quads...

**Comment by PixelRifts** [comment]
What exactly do you mean? Do you mean it a function that clips part of the quad not on screen?

**Comment by zuixalias** [comment]
I want to draw shapes inside shapes (or other objects inside shapes, like text) that, say have a parent-child relationship and the child is non-interactable if it's outside the parent region. So need to not render the child area that's outside the parent.

**Comment by PixelRifts** [comment]
I do have rectangle clipping implemented in a different renderer, I can definitely add that here.
In the meantime, if you want, check out https://github.com/PixelRifts/c-codebase/blob/master/source/opt/render_2d.c
This renderer is slightly different with multi-batches, but this does have that

**Comment by zuixalias** [comment]
Actally i am not at all familiar with computer graphics. So would need to experiment a bit for me to get anything working. (I assume `culling` is the term for `clipping`, in the link above)

Looking forward to trying it out (after i port it to my lang).
Thanks for the link, it should be of great help!

**Comment by PixelRifts** [comment]
Yup yup, I used "culling" there instead of clipping.

**Comment by PixelRifts** [comment]
I added a commit for adding clipping.
Basically, anything out of a culling_quad gets removed.
For this I clamp my vertices to be within the culling_quad boundaries.
The slightly mathy bit comes in figuring out UVs. Check out rect_uv_cull in base/vmath.c for that implementation
